name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
        node-version: ${{ matrix.node-version }}
    - run: npm cache clean --force
    - run: npm install  --force --prefix ./codebase/rdicidr-0.1.0/package.json
    - run: npm run lint --force --prefix ./codebase/rdicidr-0.1.0/package.json
    - run: npm run prettier --force --prefix ./codebase/rdicidr-0.1.0/package.json
    - run: CI=true npm run test --force --prefix ./codebase/rdicidr-0.1.0/package.json
    - run: npm run build --force --prefix ./codebase/rdicidr-0.1.0/package.json
   
