name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm install --prefix ./codebase/rdicidr-0.1.0/package.json
    - run: npm run lint --prefix ./codebase/rdicidr-0.1.0/package.json
    - run: npm run prettier --prefix ./codebase/rdicidr-0.1.0/package.json
    - run: CI=true npm run test --prefix ./codebase/rdicidr-0.1.0/package.json
    - run: npm run build --prefix ./codebase/rdicidr-0.1.0/package.json
   
