name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: path/to/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('path/to/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: cd .blob/main/codebase/rdicidr-0.1.0/package.json && npm ci
      - run: cd .blob/main/codebase/rdicidr-0.1.0/package.json && npm run lint
      - run: cd .blob/main/codebase/rdicidr-0.1.0/package.json && npm run prettier
      - run: cd .blob/main/codebase/rdicidr-0.1.0/package.json && CI=true npm run test
      - run: cd .blob/main/codebase/rdicidr-0.1.0/package.json && npm run build
